from __future__ import annotations

APPROVAL_STATUS_PENDING = "PENDING"
APPROVAL_STATUS_APPROVED = "APPROVED"
APPROVAL_STATUS_DENIED = "DENIED"
APPROVAL_STATUS_EXPIRED = "EXPIRED"
APPROVAL_STATUS_CANCELLED = "CANCELLED"

DECISION_APPROVE = "APPROVE"
DECISION_DENY = "DENY"

RISK_LOW = "low"
RISK_MEDIUM = "medium"
RISK_HIGH = "high"

METHOD_WEBAUTHN = "webauthn"
METHOD_LEDGER_WEBAUTHN = "ledger_webauthn"
METHOD_ETHEREUM_SIGNER = "ethereum_signer"

EVENT_APPROVAL_PENDING = "approval.pending"
EVENT_APPROVAL_APPROVED = "approval.approved"
EVENT_APPROVAL_DENIED = "approval.denied"
EVENT_APPROVAL_EXPIRED = "approval.expired"

VALID_DECISIONS = {DECISION_APPROVE, DECISION_DENY}
VALID_METHODS = {METHOD_WEBAUTHN, METHOD_LEDGER_WEBAUTHN, METHOD_ETHEREUM_SIGNER}
VALID_RISK_LEVELS = {RISK_LOW, RISK_MEDIUM, RISK_HIGH}
